### ISSUE TITLE
Hooked apps can detect modification

### ISSUE THREAD

**Issue by aire1** [chiteroman/BootloaderSpoofer#1]
If u try to hook Momo (special app for detecting root or etc) or any app with Xposed detection, it notices it immediately
A13, MIUI14, latest LSposed, Magisk Delta

**Comment by bengalih** [comment]
In my case, if linked Momo is fooled into thinking the bootloader is locked but will detect Zygisk and injection.

Can this be avoided?  Probably not.

**Comment by daiaji** [comment]
Indeed, Momo detected zygisk

**Comment by chiteroman** [comment]
Yep, Zygisk problem.

**Comment by aire1** [comment]
> Will be fixed in Kitsune Mask 26404

Insane. Thanks for your titanic work!

**Comment by jfcherng** [comment]
Sorry for bother but I just tried the following combination

- [R6592CA0F-kitsune (26404)](https://github.com/HuskyDG/magisk-files/releases/tag/R6592CA0F-kitsune)
- [BootloaderSpoofer v3.8](https://github.com/chiteroman/BootloaderSpoofer/releases/tag/v3.8)

Momo still detects Zygisk and injection.

**Comment by aire1** [comment]
Momo using detection based on logs. U need to install no-log version of lsp

**Comment by jfcherng** [comment]
> no-log version of lsp

Do you mean https://github.com/orgs/LSPosed/discussions/1776 ?
