### ISSUE TITLE
`3.5`->`3.6` `App not installed as package conflicts with an existing package`

### ISSUE THREAD

**Issue by brian6932** [chiteroman/BootloaderSpoofer#5]
![](https://github.com/chiteroman/BootloaderSpoofer/assets/18603393/b0eed362-21b2-4240-b9f4-039f95e3868e)
![](https://github.com/chiteroman/BootloaderSpoofer/assets/18603393/146b6db1-b674-43e5-822a-8d51a39694fc)

**Comment by furdiburd** [comment]
Same here too. Android 12

**Comment by brian6932** [comment]
I mean I did, but that shouldn't be necessary

**Comment by CapitanArdeshir** [comment]
How use this app

**Comment by chiteroman** [comment]
Using Google debug key. Now I have my own .jks
